name: nogozo
description: A new Flutter application.


publish_to:



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  english_words: ^3.1.3
  substring_highlight: 0.1.0
  shared_preferences: ^0.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:

    - images/Grocery.jpg
    - images/Electronics-Shop.png
    - images/rest.jpg
    - images/stationary.jpg
    - images/Vegetables.jpg
    - images/Veg.png
    - images/Elec.png
    - images/Resturant.png
    - images/bulb.png
    - images/Gross.webp
    - images/Dominos.jpg
    - images/VEG.jpg
    - images/cromaa.jpg
    - images/tab.png
    - images/Veggie icon.png
    - images/p3.jpg
    - images/p1.jpg
    - images/p2.jpg







  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
